<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Uplatilac;

class UplatilacReplaceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Briši sve postojeće uplatiloce
        DB::table('uplatilacs')->truncate();

        // Kompletna lista uplatioca (sifra, prezime, ime, adresa)
        $uplatilacs = [
            ['sifra' => '00001', 'ime_prezime' => 'Urošević Milka', 'adresa' => 'Zaplenska 73 Beograd'],
            ['sifra' => '00002', 'ime_prezime' => 'Knežević Zoran', 'adresa' => 'Zaplenska 73 Beograd'],
            ['sifra' => '00003', 'ime_prezime' => 'Rakić Miladin', 'adresa' => 'Puje Pandurovića Ub'],
            ['sifra' => '00004', 'ime_prezime' => 'Ilić Ljubica', 'adresa' => 'Braće Nenadovića 42 Ub'],
            ['sifra' => '00005', 'ime_prezime' => 'Birčanin Milena', 'adresa' => 'Vuka Karadžića Ub'],
            ['sifra' => '00006', 'ime_prezime' => 'Puača Milan', 'adresa' => 'Josipa Majera 41 14210 Ub'],
            ['sifra' => '00007', 'ime_prezime' => 'Đorđević Vera', 'adresa' => 'Milene Sitarice 6 Ub'],
            ['sifra' => '00008', 'ime_prezime' => 'Marković Persa', 'adresa' => 'Relje Aleksić 16 14210 Ub'],
            ['sifra' => '00009', 'ime_prezime' => 'Jeremić Zoran', 'adresa' => 'Njegoševa 4 14210 Ub'],
            ['sifra' => '00010', 'ime_prezime' => 'Živanović Miroslav', 'adresa' => 'Josipa Majera 37 Ub'],
            ['sifra' => '00011', 'ime_prezime' => 'Leontijević Stojan', 'adresa' => 'JNA 14 14210 Ub'],
            ['sifra' => '00012', 'ime_prezime' => 'Mihailović Obren', 'adresa' => 'Rajka Mihailovića Ub'],
            ['sifra' => '00013', 'ime_prezime' => 'Nikolić Božidar', 'adresa' => 'Kralja Petra Prvog 14210 Ub'],
            ['sifra' => '00014', 'ime_prezime' => 'Pjanić Slobodan', 'adresa' => 'Ratka Ranković 8 Ub'],
            ['sifra' => '00015', 'ime_prezime' => 'Živanović Miodrag', 'adresa' => 'Drinskih Divizija 14210 Ub'],
            ['sifra' => '00016', 'ime_prezime' => 'Božić Radina', 'adresa' => 'Milana Munjasa 3'],
            ['sifra' => '00017', 'ime_prezime' => 'Simić Dragan', 'adresa' => 'Braće Nenadović 14210 Ub'],
            ['sifra' => '00018', 'ime_prezime' => 'Čolić Jasna', 'adresa' => '7 Jula 5 14210 Ub'],
            ['sifra' => '00019', 'ime_prezime' => 'Krstić Jasna', 'adresa' => 'Veljka Vlahovića 9 Ub'],
            ['sifra' => '00020', 'ime_prezime' => 'Gajić Jelena', 'adresa' => 'Dušana Danilovića Ub'],
            ['sifra' => '00022', 'ime_prezime' => 'Rajšić Vera', 'adresa' => 'Josipa Majera Ub'],
            ['sifra' => '00023', 'ime_prezime' => 'Milosavljević Momir', 'adresa' => 'Braće Marčetić 314210 Ub'],
            ['sifra' => '00024', 'ime_prezime' => 'Kiselčić Aleksandar', 'adresa' => 'Tamnavska 4 14210 Ub'],
            ['sifra' => '00025', 'ime_prezime' => 'Savčić Dušan', 'adresa' => 'Milana Munjasa 14 14210 Ub'],
            ['sifra' => '00026', 'ime_prezime' => 'Marjanović Leposava', 'adresa' => 'Drinske Divizije Ub'],
            ['sifra' => '00027', 'ime_prezime' => 'Petrović Stana', 'adresa' => 'Milovana Glišića 28 A Ub'],
            ['sifra' => '00028', 'ime_prezime' => 'Stanojević Leposava', 'adresa' => 'Milana Munjasa 21 Ub'],
            ['sifra' => '00029', 'ime_prezime' => 'Mijatović Zoran', 'adresa' => 'Milana Munjasa 14210 Ub'],
            ['sifra' => '00030', 'ime_prezime' => 'Tomić Srboljub', 'adresa' => 'Živote Ilić 7'],
            ['sifra' => '00031', 'ime_prezime' => 'Jovanović Rale', 'adresa' => 'Omladinskih brigada Ub'],
            ['sifra' => '00032', 'ime_prezime' => 'Tomislav Milinković', 'adresa' => 'Kosovskih Junaka Ub'],
            ['sifra' => '00033', 'ime_prezime' => 'Lazić Srđan', 'adresa' => '3. Oktobar 6 Ub'],
            ['sifra' => '00034', 'ime_prezime' => 'Petrović Mileva', 'adresa' => '1 Maja 18 Ub'],
            ['sifra' => '00035', 'ime_prezime' => 'Milivojević Radmila', 'adresa' => 'Miloša Selakovića'],
            ['sifra' => '00036', 'ime_prezime' => 'Kostić Živka', 'adresa' => 'Radnička 29 14210 Ub'],
            ['sifra' => '00037', 'ime_prezime' => 'Mlađenović Rajna', 'adresa' => 'Miloša Markovića Ub'],
            ['sifra' => '00038', 'ime_prezime' => 'Bogićević Dragan', 'adresa' => 'Josipa Majera 31 Ub'],
            ['sifra' => '00039', 'ime_prezime' => 'Ilić Branislav', 'adresa' => 'Sveta Popović 48 14210 Ub'],
            ['sifra' => '00040', 'ime_prezime' => 'Bojanić Todor', 'adresa' => 'Svete Popović Ub'],
            ['sifra' => '00041', 'ime_prezime' => 'Obradović Milorad', 'adresa' => 'JNA 102 14210 Ub'],
            ['sifra' => '00042', 'ime_prezime' => 'Lazić Milesa', 'adresa' => 'Kralja Petra Prvog Ub'],
            ['sifra' => '00043', 'ime_prezime' => 'Lozić Dragica', 'adresa' => 'Bulevar A-8 25000 Sombor'],
            ['sifra' => '00044', 'ime_prezime' => 'Vukosavljević Ljubomir', 'adresa' => 'Dušana Danilovića 8 14210 Ub'],
            ['sifra' => '00045', 'ime_prezime' => 'Glišić Biljana', 'adresa' => 'Radnička 15 14210 Ub'],
            ['sifra' => '00046', 'ime_prezime' => 'Lepović Radosav', 'adresa' => 'Dositeja Obradovića 14 14210 Ub'],
            ['sifra' => '00048', 'ime_prezime' => 'Orozović Branka', 'adresa' => 'Josipa Majera 12 Ub'],
            ['sifra' => '00049', 'ime_prezime' => 'Lazić Dušanka', 'adresa' => 'Bratstva Jedinstva Ub'],
            ['sifra' => '00050', 'ime_prezime' => 'Nenković Ljubinka', 'adresa' => '1 Maja 91 14210 Ub'],
            ['sifra' => '00051', 'ime_prezime' => 'Ranković Vesna', 'adresa' => '1 Maja 91 Ub'],
            ['sifra' => '00052', 'ime_prezime' => 'Murić Miroslav', 'adresa' => 'JNA 60 Ub'],
            ['sifra' => '00053', 'ime_prezime' => 'Markoš Vera', 'adresa' => '1 Maja 53 Ub'],
            ['sifra' => '00054', 'ime_prezime' => 'Paripović Marija', 'adresa' => 'Petrarkina br.4 st.21 11160 Beograd'],
            ['sifra' => '00055', 'ime_prezime' => 'Paripović Tomislav', 'adresa' => 'Josipa Majera 10 Ub'],
            ['sifra' => '00056', 'ime_prezime' => 'Srećković Ljiljana', 'adresa' => 'Jovana Stoičić Zemun'],
            ['sifra' => '00057', 'ime_prezime' => 'Milutinović Aca', 'adresa' => 'Braće Nenadović 14210 Ub'],
            ['sifra' => '00058', 'ime_prezime' => 'Đurđević Dojčin', 'adresa' => 'Miloša Marković 6 Ub'],
            ['sifra' => '00059', 'ime_prezime' => 'Popović Živana', 'adresa' => 'Valjevo'],
            ['sifra' => '00060', 'ime_prezime' => 'Prodanović Danka', 'adresa' => 'Radnička 27 Ub'],
            ['sifra' => '00061', 'ime_prezime' => 'Kusalo Dejan', 'adresa' => 'Milana Munjasa 37 14210 Ub'],
            ['sifra' => '00062', 'ime_prezime' => 'Mitrović Mašinka', 'adresa' => 'Miloša Selakovića 14210 Ub'],
            ['sifra' => '00063', 'ime_prezime' => 'Vićentić Tomislav', 'adresa' => 'Veljka Vlahovića 3 UB'],
            ['sifra' => '00064', 'ime_prezime' => 'Živanović Angelina', 'adresa' => '1 Maja 1Ub'],
            ['sifra' => '00065', 'ime_prezime' => 'Luković Dušica', 'adresa' => 'Miloša Marković Ub'],
            ['sifra' => '00066', 'ime_prezime' => 'Plakalović Stana', 'adresa' => '8 Marta 12 14210 Ub'],
            ['sifra' => '00069', 'ime_prezime' => 'Popović Života', 'adresa' => 'Valjevo'],
            ['sifra' => '00070', 'ime_prezime' => 'Radišić Boro', 'adresa' => '7 Jula 1 Ub'],
            ['sifra' => '00071', 'ime_prezime' => 'Čolić Danica', 'adresa' => 'Braće Nenadovića 14210 Ub'],
            ['sifra' => '00072', 'ime_prezime' => 'Jelenić Slobodan', 'adresa' => 'Radnička 14210 Ub'],
            ['sifra' => '00073', 'ime_prezime' => 'Petrović Dragan', 'adresa' => '1 Maja 14210 Ub'],
            ['sifra' => '00074', 'ime_prezime' => 'Kaplarević Emilija', 'adresa' => 'Miloša Selakovića 9 Ub'],
            ['sifra' => '00075', 'ime_prezime' => 'Jović Miloš', 'adresa' => 'Tamnavska 11 Ub'],
            ['sifra' => '00076', 'ime_prezime' => 'Kuzeljević Ratka', 'adresa' => 'Kosovskih Junaka 14210 Ub'],
            ['sifra' => '00077', 'ime_prezime' => 'Petković Gordana', 'adresa' => 'Šarbanska 1 14210 Ub'],
            ['sifra' => '00078', 'ime_prezime' => 'Preočanin Petar', 'adresa' => 'Duška Danilovića 5 Ub'],
            ['sifra' => '00079', 'ime_prezime' => 'Pešić Biserka', 'adresa' => 'Joše Prodanovih 30  11000 Beograd'],
            ['sifra' => '00080', 'ime_prezime' => 'Petrović Borka', 'adresa' => 'Milovana Glišića 14210 Ub'],
            ['sifra' => '00081', 'ime_prezime' => 'Jakovljević Vojislav', 'adresa' => 'JNA 52 14210 Ub'],
            ['sifra' => '00082', 'ime_prezime' => 'Stefanović Dušanka', 'adresa' => 'Miloša Marković 14210 Ub'],
            ['sifra' => '00083', 'ime_prezime' => 'Banović Dragica', 'adresa' => 'Brane Petronijević Ub'],
            ['sifra' => '00084', 'ime_prezime' => 'Marković Zoran', 'adresa' => 'JNA 66  14210 Ub'],
            ['sifra' => '00085', 'ime_prezime' => 'Grubor Milka', 'adresa' => 'Svete Popović 9/1 14210 Ub'],
            ['sifra' => '00086', 'ime_prezime' => 'Panić Slobodan', 'adresa' => 'Braće Nenadović 6'],
            ['sifra' => '00087', 'ime_prezime' => 'Ikanović Biljana', 'adresa' => '28. februara 11 14210 Ub'],
            ['sifra' => '00088', 'ime_prezime' => 'Urošević Saša', 'adresa' => 'Čede Minderović14210 Ub'],
            ['sifra' => '00089', 'ime_prezime' => 'Jezdimirović Ivan', 'adresa' => 'Milana Munjasa 14210 Ub'],
            ['sifra' => '00090', 'ime_prezime' => 'Đurić Živorad', 'adresa' => 'Josipa Majera 14210 Ub'],
            ['sifra' => '00091', 'ime_prezime' => 'Lazić Slobodan', 'adresa' => 'Josipa Majera 27 Ub'],
            ['sifra' => '00092', 'ime_prezime' => 'Belajac Dušan', 'adresa' => 'Svete Popović Ub'],
            ['sifra' => '00093', 'ime_prezime' => 'Jevtić Milivoje', 'adresa' => 'Živote Ilić 1 Ub'],
            ['sifra' => '00094', 'ime_prezime' => 'Jovanović Mirjana', 'adresa' => 'JNA 14210 Ub'],
            ['sifra' => '00095', 'ime_prezime' => 'Milovanović Miloš', 'adresa' => 'Školska 5 14210 Ub'],
            ['sifra' => '00096', 'ime_prezime' => 'Njagrić Milena', 'adresa' => 'Braće Nenadović Ub'],
            ['sifra' => '00097', 'ime_prezime' => 'Lukić Ljiljana', 'adresa' => 'Braće Nenadović Ub'],
            ['sifra' => '00098', 'ime_prezime' => 'Mijatović Julijana', 'adresa' => 'Radnička 11 14210 Ub'],
            ['sifra' => '00099', 'ime_prezime' => 'Ranković Dragan', 'adresa' => 'Braće Nenadović 14210 Ub'],
            ['sifra' => '00100', 'ime_prezime' => 'Petković Sanja', 'adresa' => 'R Ranković 14210 Ub'],
            ['sifra' => '00101', 'ime_prezime' => 'Kovačević Milojka', 'adresa' => 'Braće Nenadović 32 Ub'],
            ['sifra' => '00102', 'ime_prezime' => 'Popović Dragan', 'adresa' => 'Braće Nenadović 53 Ub'],
            ['sifra' => '00103', 'ime_prezime' => 'Pantelić Radmila', 'adresa' => 'JNA 51'],
            ['sifra' => '00104', 'ime_prezime' => 'Mirković Jovan', 'adresa' => 'Moše Pijade 19  14210 Ub'],
            ['sifra' => '00105', 'ime_prezime' => 'Nikolić Nikola', 'adresa' => 'Marka Milanović 9 Obrenovac'],
            ['sifra' => '00106', 'ime_prezime' => 'Stanić Siniša', 'adresa' => 'Milana Munjasa 32 Ub'],
            ['sifra' => '00107', 'ime_prezime' => 'Blagojević Branko', 'adresa' => 'Školska 19 Ub'],
            ['sifra' => '00108', 'ime_prezime' => 'Radovanović Ilinka', 'adresa' => 'Braće Nenadović 64'],
            ['sifra' => '00109', 'ime_prezime' => 'Vujić Dragoslav', 'adresa' => '10. Nova 70 Borča'],
            ['sifra' => '00110', 'ime_prezime' => 'Bosiljčić Milan', 'adresa' => 'JNA 6 Ub'],
            ['sifra' => '00111', 'ime_prezime' => 'Cerović Olga', 'adresa' => 'Svete Popović 4 UB'],
            ['sifra' => '00112', 'ime_prezime' => 'Kesić Milana', 'adresa' => 'Prvog Maja 43 Ub'],
            ['sifra' => '00113', 'ime_prezime' => 'Jovanović Mira', 'adresa' => 'Milana Munjasa 5 Ub'],
            ['sifra' => '00114', 'ime_prezime' => 'Bojanić Radmila', 'adresa' => 'Banjanska 1 14210 Ub'],
            ['sifra' => '00115', 'ime_prezime' => 'Nikolić Milka', 'adresa' => 'Bulevar  Zorana Đinđića 86/45 N.Beograd'],
            ['sifra' => '00116', 'ime_prezime' => 'Kurbalija Desanka', 'adresa' => 'Maršala Birjuzova 49 Beograd'],
            ['sifra' => '00117', 'ime_prezime' => 'Velimirović Radovinka', 'adresa' => 'Lamela 5/1'],
            ['sifra' => '00118', 'ime_prezime' => 'Nešić Miloš', 'adresa' => 'Kičevska 20 Beograd'],
            ['sifra' => '00119', 'ime_prezime' => 'Jovanović Ljubica', 'adresa' => 'Jove Ilića 97 Beograd'],
            ['sifra' => '00120', 'ime_prezime' => 'Paramentić Ivanka', 'adresa' => '3. oktobra 6 Ub'],
            ['sifra' => '00121', 'ime_prezime' => 'Tasić Radojica', 'adresa' => 'Svete Popovića 87/1'],
            ['sifra' => '00122', 'ime_prezime' => 'Đokić Branka', 'adresa' => 'Birčaninova 64 14000 Valjevo'],
            ['sifra' => '00123', 'ime_prezime' => 'Stevanović Ljiljana', 'adresa' => 'Milovana Glišića 7'],
            ['sifra' => '00125', 'ime_prezime' => 'Žnidarčić Milan', 'adresa' => 'Ive Lole Ribara 11'],
            ['sifra' => '00126', 'ime_prezime' => 'Petrović Ljubomir', 'adresa' => 'Vojvode Mišića 26 14210 Ub'],
            ['sifra' => '00127', 'ime_prezime' => 'Petrović Milorad', 'adresa' => 'Braće Nenadović 6 14210 Ub'],
            ['sifra' => '00128', 'ime_prezime' => 'Nenković Ljubinka', 'adresa' => '1 Maja 91 UB'],
            ['sifra' => '00129', 'ime_prezime' => 'Bošković Ljubica', 'adresa' => 'Svete Popović'],
            ['sifra' => '00130', 'ime_prezime' => 'Kokotović Ljubomir', 'adresa' => '1 Maja 55'],
            ['sifra' => '00131', 'ime_prezime' => 'Janjić Nenad', 'adresa' => 'Sestara Rebavki 3/3 14210 Ub'],
            ['sifra' => '00132', 'ime_prezime' => 'Stamenković Stanica', 'adresa' => '13 Proleterske Ub'],
            ['sifra' => '00133', 'ime_prezime' => 'Selaković Miloš', 'adresa' => 'Kralja Petra Oslobodioca 17 Ub'],
            ['sifra' => '00134', 'ime_prezime' => 'Lazić Ljiljana', 'adresa' => 'Alekse Martić 12 Ub'],
            ['sifra' => '00135', 'ime_prezime' => 'Starčević Živomir', 'adresa' => 'Tamnavska Ub'],
            ['sifra' => '00136', 'ime_prezime' => 'Ječmenica Radosav', 'adresa' => '28 Februara 14210 Ub'],
            ['sifra' => '00137', 'ime_prezime' => 'Starčević Milorad', 'adresa' => 'Tamnavska 6/8 14210 Ub'],
            ['sifra' => '00138', 'ime_prezime' => 'Milošević Milan', 'adresa' => 'Vuka Karadžića 40 14210 Ub'],
            ['sifra' => '00139', 'ime_prezime' => 'Maljković Ljiljana', 'adresa' => 'Maksima Gorkog 48 Novi Sad 21000'],
            ['sifra' => '00140', 'ime_prezime' => 'Simić Dragan', 'adresa' => 'Kralja Petra Oslobodioca Ub'],
            ['sifra' => '00141', 'ime_prezime' => 'Kujundžić Milijana', 'adresa' => '1 Maja 171 Ub'],
            ['sifra' => '00142', 'ime_prezime' => 'Petrović Mitar', 'adresa' => 'Milana Mihailović 14210 Ub'],
            ['sifra' => '00143', 'ime_prezime' => 'Nikolić Draginja', 'adresa' => 'Tamnavska 14210 Ub'],
            ['sifra' => '00144', 'ime_prezime' => 'Perišić Natalija', 'adresa' => 'Kralja Petra Oslobodioca Ub'],
            ['sifra' => '00145', 'ime_prezime' => 'Alimpijević Svetlana', 'adresa' => 'Bul. Umetnosti 17 I ulaz stan 20 N. Beograd'],
            ['sifra' => '00146', 'ime_prezime' => 'Andrić Marko', 'adresa' => 'D Simić 9 Ub'],
            ['sifra' => '00148', 'ime_prezime' => 'Popović Radoslav', 'adresa' => 'Miloša Selakovića Ub'],
            ['sifra' => '00149', 'ime_prezime' => 'Dimitrijević Dragomir', 'adresa' => 'Radnička 5 14210 Ub'],
            ['sifra' => '00150', 'ime_prezime' => 'Grujičić Slobodanka', 'adresa' => 'Josipa Majera 78 14210 Ub'],
            ['sifra' => '00151', 'ime_prezime' => 'Urukalo Gradimir', 'adresa' => 'Svete Popović Ub'],
            ['sifra' => '00152', 'ime_prezime' => 'Knežević Dragica', 'adresa' => 'Drinske Divizije 3/1 14210 Ub'],
            ['sifra' => '00154', 'ime_prezime' => 'Radojičić Ružica', 'adresa' => 'Milana Mihailović 6 14210 Ub'],
            ['sifra' => '00155', 'ime_prezime' => 'Lazarević Živorad', 'adresa' => 'Milana Munjasa 14210 Ub'],
            ['sifra' => '00156', 'ime_prezime' => 'Pantelić Milenija', 'adresa' => '3. Oktobra Ub'],
            ['sifra' => '00157', 'ime_prezime' => 'Raković Vladislav', 'adresa' => 'Dobrosava Simića 6 14210 Ub'],
    ['sifra' => '00158', 'ime_prezime' => 'Radojević Radič', 'adresa' => 'Pop Lukina 35 14000 Valjevo'],
    ['sifra' => '00159', 'ime_prezime' => 'Dimitrijević Natalija', 'adresa' => 'Miloša Obrenovića 27 Obrenovac'],
    ['sifra' => '00160', 'ime_prezime' => 'Krnjajić Darinka', 'adresa' => 'Miloša Marković br.5 Ub'],
    ['sifra' => '00161', 'ime_prezime' => 'Lazić Dragica', 'adresa' => 'Prvomajski Bulevar Avnoja 8 Sombor'],
    ['sifra' => '00162', 'ime_prezime' => 'Jovanović Slobodan', 'adresa' => 'Milića Bučić 20 Ub'],
    ['sifra' => '00163', 'ime_prezime' => 'Stefanović Ljubinka', 'adresa' => '1. Maja'],
    ['sifra' => '00164', 'ime_prezime' => 'Kostić Andrija', 'adresa' => 'Severni Bulevar Beograd 2 19/3 11200'],
    ['sifra' => '00165', 'ime_prezime' => 'Mijatović Živorad', 'adresa' => 'Svete Popović 43 14210 Ub'],
    ['sifra' => '00166', 'ime_prezime' => 'Milićević Aleksandar', 'adresa' => 'Relje Aleksić 14 14210 Ub'],
    ['sifra' => '00167', 'ime_prezime' => 'Raonić Danojla', 'adresa' => 'Radomira Sofronića 5 14210 Ub'],
    ['sifra' => '00168', 'ime_prezime' => 'Nikolić Grozdana', 'adresa' => 'Vuka Karadžića 38 14210 Ub'],
    ['sifra' => '00169', 'ime_prezime' => 'Stojčić Dragica', 'adresa' => 'Braće Nenadović 5 Ub'],
    ['sifra' => '00170', 'ime_prezime' => 'Vukosavljević Negomirka', 'adresa' => 'Braće Nenadović 14210 Ub'],
    ['sifra' => '00171', 'ime_prezime' => 'Cvijović Slobodanka', 'adresa' => 'Josipa Majera Ub'],
    ['sifra' => '00172', 'ime_prezime' => 'Simić Ljubomir', 'adresa' => 'Dragomira Ostojića 58 Kragujevac'],
    ['sifra' => '00173', 'ime_prezime' => 'Paripović Jelena', 'adresa' => 'Milovana Glišića 14210 Ub'],
    ['sifra' => '00174', 'ime_prezime' => 'Mitrović Marija', 'adresa' => 'Šarbanska 3 14210 Ub'],
    ['sifra' => '00175', 'ime_prezime' => 'Spasić-Vuković Dragica', 'adresa' => 'Mileševska 14/14 Beograd'],
    ['sifra' => '00176', 'ime_prezime' => 'Vasiljević Srboljub', 'adresa' => 'JNA 67 14210 Ub'],
    ['sifra' => '00177', 'ime_prezime' => 'Jadžić Zora', 'adresa' => 'Trnjaci 14210 Ub'],
    ['sifra' => '00178', 'ime_prezime' => 'Stojković Života', 'adresa' => 'Dobrosava Simić 14210 Ub'],
    ['sifra' => '00179', 'ime_prezime' => 'Marjanović Jela', 'adresa' => 'Prvog Maja 14210 Ub'],
    ['sifra' => '00180', 'ime_prezime' => 'Martić Danka', 'adresa' => 'Milana Munjasa 14210 Ub'],
    ['sifra' => '00181', 'ime_prezime' => 'Stefanović Milica', 'adresa' => 'JNA 98 14210 Ub'],
    ['sifra' => '00182', 'ime_prezime' => 'Vukosavljević Dragan', 'adresa' => 'Bogdanovica 14210 Ub'],
    ['sifra' => '00183', 'ime_prezime' => 'Blagojević Ljiljana', 'adresa' => 'Knez Danilova 52 Beograd'],
    ['sifra' => '00184', 'ime_prezime' => 'Spasojević Verka', 'adresa' => 'Pere Todorović 28 11030 Banovo brdo'],
    ['sifra' => '00185', 'ime_prezime' => 'Ranković Manja', 'adresa' => 'Kralja Petra 41 14210 Ub'],
    ['sifra' => '00186', 'ime_prezime' => 'Denda Ljiljana', 'adresa' => 'Marka Čelebonovića 65/27 11070 Novi Beograd'],
    ['sifra' => '00187', 'ime_prezime' => 'Jeremić Radovan', 'adresa' => 'Prvog Maja Ub'],
    ['sifra' => '00189', 'ime_prezime' => 'Kovačević Milena', 'adresa' => 'Bratstva Jedinstva 14210 Ub'],
    ['sifra' => '00190', 'ime_prezime' => 'Ranković Verica', 'adresa' => '30 Juna br.3 14210 Ub'],
    ['sifra' => '00191', 'ime_prezime' => 'Vulešević Zoran', 'adresa' => 'Beograd'],
    ['sifra' => '00192', 'ime_prezime' => 'Jovanović Ljiljana', 'adresa' => 'Čede Todorović 14210 Ub'],
    ['sifra' => '00193', 'ime_prezime' => 'Mihailović Milanka', 'adresa' => 'Milovana Glišić 23 Ub'],
    ['sifra' => '00194', 'ime_prezime' => 'Perić Dragan', 'adresa' => 'Braće Nenadović 160 14210 Ub'],
    ['sifra' => '00195', 'ime_prezime' => 'Baratović Miroslav', 'adresa' => 'Milana Mihailović 18/1 14210 Ub'],
    ['sifra' => '00196', 'ime_prezime' => 'Marković Dejan', 'adresa' => 'Milovana Glišić 5 14210 Ub'],
    ['sifra' => '00198', 'ime_prezime' => 'Jovanović Miloš', 'adresa' => 'R.Plaović 16'],
    ['sifra' => '00199', 'ime_prezime' => 'Kadijević Dragomir', 'adresa' => 'Tvrdojevac 14210 Ub'],
    ['sifra' => '00202', 'ime_prezime' => 'Živković Miloš', 'adresa' => 'Vuka Karadžića 28 14210 Ub'],
    ['sifra' => '00203', 'ime_prezime' => 'Ristivojević Milka', 'adresa' => 'Prvog Maja 120 14210 Ub'],
    ['sifra' => '00204', 'ime_prezime' => 'Lazić Branko', 'adresa' => 'Lajkovac'],
    ['sifra' => '00205', 'ime_prezime' => 'Marković Ivana', 'adresa' => 'Dobrosava Simić 14210 Ub'],
    ['sifra' => '00206', 'ime_prezime' => 'Čolić Milovan', 'adresa' => 'K.P.Oslobodioca 14210 Ub'],
    ['sifra' => '00207', 'ime_prezime' => 'Lučić Jela', 'adresa' => 'Braće Nenadović Ub'],
    ['sifra' => '00208', 'ime_prezime' => 'Ivković Marina', 'adresa' => 'Stubline 11507 Stubline'],
    ['sifra' => '00209', 'ime_prezime' => 'Filipović Živka', 'adresa' => 'Prvog Maja 14210 Ub'],
    ['sifra' => '00211', 'ime_prezime' => 'Urošević Ivana', 'adresa' => 'Školska br.15 14210 Ub'],
    ['sifra' => '00212', 'ime_prezime' => 'Ilić Jelena', 'adresa' => 'Braće Nenadović 12 14210 Ub'],
    ['sifra' => '00213', 'ime_prezime' => 'Ilić Željko', 'adresa' => 'Radnička 28 14210 Ub'],
    ['sifra' => '00214', 'ime_prezime' => 'Filipović Živka', 'adresa' => 'Prvog Maja 14210 Ub'],
    ['sifra' => '00215', 'ime_prezime' => 'Stajčić Živka', 'adresa' => 'Svete Popović 31 14210 Ub'],
    ['sifra' => '00216', 'ime_prezime' => 'Pavlović Nada', 'adresa' => 'Milene Sitarice 14210 Ub'],
    ['sifra' => '00217', 'ime_prezime' => 'Šimšić Srećko', 'adresa' => 'Prote Mateje 1 14210 Ub'],
    ['sifra' => '00218', 'ime_prezime' => 'Đurić Milka', 'adresa' => 'Prvog Maja 26 14210 Ub'],
    ['sifra' => '00219', 'ime_prezime' => 'Vlajković Milka', 'adresa' => 'Lamela 2/11 14210 Ub'],
    ['sifra' => '00220', 'ime_prezime' => 'Antić Jovan', 'adresa' => 'Beograd Mileševska 17a'],
    ['sifra' => '00221', 'ime_prezime' => 'Milićević Nikola', 'adresa' => 'Beograd Vojvode Stepe 38'],
    ['sifra' => '00222', 'ime_prezime' => 'Toković Aleksandar', 'adresa' => 'JNA 43 14210 Ub'],
    ['sifra' => '00223', 'ime_prezime' => 'Terzić Ljubica', 'adresa' => 'Josipa Majera 34 14210 Ub'],
    ['sifra' => '00224', 'ime_prezime' => 'Runjaić Gordana', 'adresa' => 'Josipa Majera 20 Ub'],
    ['sifra' => '00225', 'ime_prezime' => 'Atlić Vera', 'adresa' => '29 Novembra 5 14210 Ub'],
    ['sifra' => '00226', 'ime_prezime' => 'Mijailović Zoran', 'adresa' => 'Ive Lole Ribara br.3 14210 Ub'],
    ['sifra' => '00227', 'ime_prezime' => 'Jovanović Milena', 'adresa' => 'Alekse Martić 2/1314210 Ub'],
    ['sifra' => '00228', 'ime_prezime' => 'Stojanović Dragan', 'adresa' => 'Braće Nenadović Ub 14210 Ub'],
    ['sifra' => '00229', 'ime_prezime' => 'Đunisijević Gordana', 'adresa' => 'K.P.Oslobodioca 14210 Ub'],
    ['sifra' => '00230', 'ime_prezime' => 'Sajić Grozdana', 'adresa' => 'Braćen Nenadović 23 14210 Ub'],
    ['sifra' => '00231', 'ime_prezime' => 'Jelić Slavica', 'adresa' => 'Karađorđeva br.3 14210 Ub'],
    ['sifra' => '00232', 'ime_prezime' => 'Perić Ljiljana', 'adresa' => 'Braće Jovanović 3 14210 Ub'],
    ['sifra' => '00233', 'ime_prezime' => 'Blagojević Anka', 'adresa' => 'Prvog Maja 12 14210 Ub'],
    ['sifra' => '00234', 'ime_prezime' => 'Savić Ljubica', 'adresa' => 'Radnička 74 14210 Ub'],
    ['sifra' => '00235', 'ime_prezime' => 'Purić Stana', 'adresa' => 'Solunskih Ratnika br.3 14210 Ub'],
    ['sifra' => '00236', 'ime_prezime' => 'Rajković Verica', 'adresa' => 'Dušana Petronijević 17 Beograd'],
    ['sifra' => '00237', 'ime_prezime' => 'Filipović Svetlana', 'adresa' => 'Gandijeva 85 11070 Novi Beograd'],
    ['sifra' => '00238', 'ime_prezime' => 'Stankov Slavica', 'adresa' => 'Gojka Doronjskog 14210 Ub'],
    ['sifra' => '00239', 'ime_prezime' => 'Božilović Goran', 'adresa' => 'Ive Lole Ribara 22 14210 Ub'],
    ['sifra' => '00240', 'ime_prezime' => 'Kovačević Marija', 'adresa' => 'Milovana Glišić br.21 14210 Ub'],
    ['sifra' => '00241', 'ime_prezime' => 'Teodosić Mirko', 'adresa' => 'Kosovskih Junaka 25 14210 Ub'],
    ['sifra' => '00242', 'ime_prezime' => 'Simić Dobrila', 'adresa' => 'Luja Adamiča 26/13 11070 N.Beograd'],
    ['sifra' => '00243', 'ime_prezime' => 'Siljanović Radomir', 'adresa' => 'Radnička 8 14210 Ub'],
    ['sifra' => '00244', 'ime_prezime' => 'Nikolić Radenko', 'adresa' => 'Prvog Maja 142 14210 Ub'],
    ['sifra' => '00245', 'ime_prezime' => 'Paripović Gordana', 'adresa' => 'Milana Munjasa 12 14210 Ub'],
    ['sifra' => '00246', 'ime_prezime' => 'Mirković Božidar', 'adresa' => 'JNA 30 14210 Ub'],
    ['sifra' => '00247', 'ime_prezime' => 'Matić Milesa', 'adresa' => 'Banjanska 6 14210 Ub'],
    ['sifra' => '00248', 'ime_prezime' => 'Simić Biljana', 'adresa' => 'Lamela IV/21 14210 Ub'],
    ['sifra' => '00249', 'ime_prezime' => 'Petrović Periša', 'adresa' => 'Kralja Petra Oslob.14210 Ub'],
    ['sifra' => '00250', 'ime_prezime' => 'Dimitrijević Marija', 'adresa' => 'Milana Munjasa 62 14210 Ub'],
    ['sifra' => '00251', 'ime_prezime' => 'Milunić Jovan', 'adresa' => 'Studentski Trg 17/1-Beograd'],
    ['sifra' => '00252', 'ime_prezime' => 'Jakovljević Zorica', 'adresa' => 'Tamnavska br.11 14210 Ub'],
    ['sifra' => '00253', 'ime_prezime' => 'Kostić Zlata', 'adresa' => 'Kralja Petra I Oslobodioca'],
    ['sifra' => '00254', 'ime_prezime' => 'Nikolić Julka', 'adresa' => 'Kralja Petra Oslobodioca I 14210 Ub'],
    ['sifra' => '00255', 'ime_prezime' => 'Đokić Olivera', 'adresa' => 'K.P.Oslobodioca 27 Ub'],
    ['sifra' => '00256', 'ime_prezime' => 'Lazić Ljubivoj', 'adresa' => 'Raše Plaović 17 14210 Ub'],
    ['sifra' => '00257', 'ime_prezime' => 'Jovanović Nemanja', 'adresa' => 'Prvog Maja 71 14210 Ub'],
    ['sifra' => '00258', 'ime_prezime' => 'Petrović Ivan', 'adresa' => 'Grobljanska br.9 14210 Ub'],
    ['sifra' => '00259', 'ime_prezime' => 'Lukić Kosovka', 'adresa' => 'Osečina Valjevo'],
    ['sifra' => '00260', 'ime_prezime' => 'Lazić Srđan', 'adresa' => 'Trećeg oktobra3 14210 Ub'],
    ['sifra' => '00262', 'ime_prezime' => 'Pavlović Milenko', 'adresa' => 'Dobrosava Simića Ub'],
    ['sifra' => '00263', 'ime_prezime' => 'Vagić Dušan', 'adresa' => 'Milana Munjasa 64 Ub'],
    ['sifra' => '00264', 'ime_prezime' => 'Popović Rajko', 'adresa' => 'Vlade Danilović 1/4 Valjevo'],
    ['sifra' => '00265', 'ime_prezime' => 'Munjas Stana', 'adresa' => 'Milana Munjasa 39 Ub'],
    ['sifra' => '00266', 'ime_prezime' => 'Milinčević Slobodanka', 'adresa' => 'Svete Popović 93 Ub'],
    ['sifra' => '00267', 'ime_prezime' => 'Marković Rosa', 'adresa' => 'Josipa Majera Ub'],
    ['sifra' => '00268', 'ime_prezime' => 'Živanović Milan', 'adresa' => 'Kolubarska br.3 Ub'],
    ['sifra' => '00270', 'ime_prezime' => 'Teofanov Baratović Gordana', 'adresa' => 'Jugovićevo Sokače 7 23300 Kikinda'],
    ['sifra' => '00271', 'ime_prezime' => 'Popović Veselina Milan', 'adresa' => 'Milana Munjasa br.6 Ub'],
    ['sifra' => '00272', 'ime_prezime' => 'Šipčić Nada', 'adresa' => 'JNA 40 Ub'],
    ['sifra' => '00273', 'ime_prezime' => 'Jevtić Nada', 'adresa' => 'Vuka Karadžića 14'],
    ['sifra' => '00274', 'ime_prezime' => 'Vasović Zoran', 'adresa' => 'Rajka Mihailović14210 Ub'],
    ['sifra' => '00275', 'ime_prezime' => 'Miler Ljubica', 'adresa' => 'JNA 64 Ub'],
    ['sifra' => '00276', 'ime_prezime' => 'Ječmenica Živana', 'adresa' => 'Radnička 14 Ub'],
    ['sifra' => '00277', 'ime_prezime' => 'Živković Milena', 'adresa' => 'Ilije Garašanina br.15 11000 Beograd'],
    ['sifra' => '00278', 'ime_prezime' => 'Stepanović Radomir', 'adresa' => 'JNA 109 Ub'],
    ['sifra' => '00279', 'ime_prezime' => 'Stanisavljević Biljana', 'adresa' => 'Vojvode Putnika 40 Obrenovac 11500'],
    ['sifra' => '00281', 'ime_prezime' => 'Ilić Mileta', 'adresa' => 'Radnička Ub'],
    ['sifra' => '00282', 'ime_prezime' => 'Paunović Dragica', 'adresa' => 'Slavoljuba Milivojevića 6 Ub'],
    ['sifra' => '00283', 'ime_prezime' => 'Jovanović Tomislav', 'adresa' => 'Braće Jovanović 6 UB'],
    ['sifra' => '00284', 'ime_prezime' => 'Milanović M. Milan', 'adresa' => 'Vrelo Ub'],
    ['sifra' => '00285', 'ime_prezime' => 'Krsmanović Dragica', 'adresa' => 'Radnička 35 14210 Ub'],
    ['sifra' => '00286', 'ime_prezime' => 'Hadžić Milica', 'adresa' => 'Nušićeva 15/2 V aljevo'],
    ['sifra' => '00287', 'ime_prezime' => 'Đorđević Mihailo', 'adresa' => '5188 Meridian Ave San Jose Ca118'],
    ['sifra' => '00288', 'ime_prezime' => 'Jelenić Jelena', 'adresa' => 'Braće Nenadović 40 14210 Ub'],
    ['sifra' => '00289', 'ime_prezime' => 'Perišić Miroslav', 'adresa' => 'Trnjaci 14210 Ub'],
    ['sifra' => '00290', 'ime_prezime' => 'Murić Gordana', 'adresa' => 'Dositeja Obradović'],
    ['sifra' => '00291', 'ime_prezime' => 'Vukosavljević Božanka', 'adresa' => '3 Oktobra 6/10 Ub'],
    ['sifra' => '00292', 'ime_prezime' => 'Janković Dragoljub', 'adresa' => 'Josipa Majera 14210 Ub'],
    ['sifra' => '00293', 'ime_prezime' => 'Novaković Milutin', 'adresa' => 'Karaburma II Novi beograd'],
    ['sifra' => '00294', 'ime_prezime' => 'Jelić Duško', 'adresa' => 'Sinđelićeva 1 14000 Valjevo'],
    ['sifra' => '00295', 'ime_prezime' => 'Vučičević Zorica', 'adresa' => 'Radljevo Ub'],
    ['sifra' => '00296', 'ime_prezime' => 'Vodoplav Stojan', 'adresa' => 'Svetozara Marković 9 11000 Beograd'],
    ['sifra' => '00297', 'ime_prezime' => 'Milovanović Branislav', 'adresa' => 'Obalskih Radnika 25 11030 Čukarica'],
    ['sifra' => '00298', 'ime_prezime' => 'Maciejonczyk Ruža', 'adresa' => 'Ub Slavoljuba Milivojević 4'],
    ['sifra' => '00299', 'ime_prezime' => 'Jadžić Dobrivoje', 'adresa' => 'Bratstva Jedinstva 14210 Ub'],
    ['sifra' => '00300', 'ime_prezime' => 'Josipović Milan', 'adresa' => 'Braće Nenadović 65 Ub'],
    ['sifra' => '00301', 'ime_prezime' => 'Đokić Ratibor', 'adresa' => 'Kneza Miloša 18 14000 Valjevo'],
    ['sifra' => '00302', 'ime_prezime' => 'Popadić Dr.Zaviša', 'adresa' => 'Zemun Save Burića br.4 11080 Beograd'],
    ['sifra' => '00303', 'ime_prezime' => 'Lazić Dragan', 'adresa' => 'Barič 11504 Barič'],
    ['sifra' => '00304', 'ime_prezime' => 'Simić Prvoslav', 'adresa' => 'Kapetana Popovića br.2 11000 Beograd'],
    ['sifra' => '00305', 'ime_prezime' => 'Ilić Dragoljub', 'adresa' => 'Dušana Danilović 14210 Ub'],
    ['sifra' => '00306', 'ime_prezime' => 'Petrović Milunka', 'adresa' => 'Prvog Maja 70 14210 Ub'],
    ['sifra' => '00307', 'ime_prezime' => 'Martić Milutin', 'adresa' => 'Milana Munjasa 40 Ub'],
    ['sifra' => '00308', 'ime_prezime' => 'Ilišković Slobodanka', 'adresa' => 'Beograd'],
    ['sifra' => '00310', 'ime_prezime' => 'Simić Zoran', 'adresa' => 'K.P.Oslobodioca 14210 Ub'],
    ['sifra' => '00311', 'ime_prezime' => 'Vujić Radosav', 'adresa' => 'Milana Munjasa br.43 Ub'],
    ['sifra' => '00312', 'ime_prezime' => 'Jelisavčić Ljiljana', 'adresa' => 'Karađorđeva 10 Bajina Bašta 31250'],
    ['sifra' => '00313', 'ime_prezime' => 'Andrić Stana', 'adresa' => 'D.Danilović 10 14210 Ub'],
    ['sifra' => '00315', 'ime_prezime' => 'Bogićević Tomislav', 'adresa' => 'D.Danilovića 7 Ub'],
    ['sifra' => '00316', 'ime_prezime' => 'Arsić Stanisavljević Jelica', 'adresa' => 'Radnička 5/G 11030 Beograd'],
    ['sifra' => '00317', 'ime_prezime' => 'Vasiljević Predrag', 'adresa' => 'D.Danilovića 9 14210 Ub'],
    ['sifra' => '00318', 'ime_prezime' => 'Biondić Ivan', 'adresa' => 'Raše Plaović 9 14210 Ub'],
    ['sifra' => '00320', 'ime_prezime' => 'Radovanović Radoslav', 'adresa' => 'D.Simića 5 14210 Ub'],
    ['sifra' => '00321', 'ime_prezime' => 'Milićević Živorad', 'adresa' => 'D.Simića 11 14210 Ub'],
    ['sifra' => '00322', 'ime_prezime' => 'Lučić Milijana', 'adresa' => 'D.Simića 13 14210 Ub'],
    ['sifra' => '00323', 'ime_prezime' => 'Stojković Olga', 'adresa' => 'D.Simića 14210 Ub'],
    ['sifra' => '00324', 'ime_prezime' => 'Krstić Slavica', 'adresa' => 'D.Simića 10 14210 Ub'],
    ['sifra' => '00325', 'ime_prezime' => 'Vladisavljević Petar', 'adresa' => 'D.Simića 8 14210 Ub'],
    ['sifra' => '00326', 'ime_prezime' => 'Todorović LJiljana', 'adresa' => 'V.Karadžića 13 Ub'],
    ['sifra' => '00327', 'ime_prezime' => 'Tešić Dejan', 'adresa' => 'V.Karadžića 11 14210 Ub'],
    ['sifra' => '00328', 'ime_prezime' => 'Veselinović LJiljana', 'adresa' => 'V.Karadžića 2 Ub'],
    ['sifra' => '00329', 'ime_prezime' => 'Gojković Milan', 'adresa' => 'V.Karadžića 3 14210 Ub'],
    ['sifra' => '00330', 'ime_prezime' => 'Savković Milivoj', 'adresa' => 'V.Karadžića 14210 Ub'],
    ['sifra' => '00331', 'ime_prezime' => 'Milekić Leposava', 'adresa' => 'V.Karadžića 42 14210 Ub'],
    ['sifra' => '00332', 'ime_prezime' => 'Krstić Nataša', 'adresa' => 'V.Karadžića 14210 Ub'],
    ['sifra' => '00333', 'ime_prezime' => 'Velimirović Branka', 'adresa' => 'V.Karadžića 24'],
    ['sifra' => '00334', 'ime_prezime' => 'Matić Velja', 'adresa' => '28 Februara Ub'],
    ['sifra' => '00335', 'ime_prezime' => 'Grčić Rosa', 'adresa' => '28 Februara14210 Ub'],
    ['sifra' => '00336', 'ime_prezime' => 'Radojčić Bisa', 'adresa' => '28 Februara 14210 Ub'],
    ['sifra' => '00337', 'ime_prezime' => 'Lazić Slobodan', 'adresa' => 'Milana Munjasa 95 Ub'],
    ['sifra' => '00338', 'ime_prezime' => 'Ilić Milena', 'adresa' => 'Prvog Maja 52 14210 Ub'],
    ['sifra' => '00339', 'ime_prezime' => 'Pantelić Milesa', 'adresa' => 'Prvog Maja 40 14210 Ub'],
    ['sifra' => '00340', 'ime_prezime' => 'Daković Slavica', 'adresa' => 'Radnička 48 /1 11030 BEOGRAD'],
    ['sifra' => '00341', 'ime_prezime' => 'Ninković Mirko', 'adresa' => 'B.Jedinstva 50 14210 Ub'],
    ['sifra' => '00342', 'ime_prezime' => 'Martić Gordana', 'adresa' => 'B.i Jedinstva 42 14210 Ub'],
    ['sifra' => '00343', 'ime_prezime' => 'Teofilović Dragan', 'adresa' => 'B: i Jedinstva 14210 Ub'],
    ['sifra' => '00344', 'ime_prezime' => 'Petrović Andrija', 'adresa' => 'B. i Jedinstva 36 14210 Ub'],
    ['sifra' => '00345', 'ime_prezime' => 'Lazić Slavka', 'adresa' => 'B. i Jedinstva 14210 Ub'],
    ['sifra' => '00346', 'ime_prezime' => 'Mijailović Snežana', 'adresa' => 'B. i Jedinstva Ub'],
    ['sifra' => '00347', 'ime_prezime' => 'Radojičić Vladimir', 'adresa' => 'B. i Jedinstva 27 14210 Ub'],
    ['sifra' => '00348', 'ime_prezime' => 'Ninković Sreten', 'adresa' => 'B. i Jedinstva 14210 Ub'],
    ['sifra' => '00349', 'ime_prezime' => 'Jovanović Milka', 'adresa' => 'B. i Jedinstva 54 14210 Ub'],
    ['sifra' => '00350', 'ime_prezime' => 'Jovanović Sreten', 'adresa' => 'B. i Jedinstva 14210 Ub'],
    ['sifra' => '00351', 'ime_prezime' => 'Atlić Radovan', 'adresa' => 'B i Jedinstva 14210 Ub'],
    ['sifra' => '00352', 'ime_prezime' => 'Aleksandrić Josip', 'adresa' => 'B. i Jedinstva 14210 Ub'],
    ['sifra' => '00353', 'ime_prezime' => 'Višnjić Katarina', 'adresa' => 'B.i jedinstva 14210 Ub'],
    ['sifra' => '00354', 'ime_prezime' => 'Aksić Radoje', 'adresa' => 'B. i Jedinastva 14210 Ub'],
    ['sifra' => '00355', 'ime_prezime' => 'Grmušić Slobodan', 'adresa' => 'B. i Jedinstva 14210 Ub'],
    ['sifra' => '00356', 'ime_prezime' => 'Ranković Živodarka', 'adresa' => '1 Maja br.61 14210 Ub'],
    ['sifra' => '00357', 'ime_prezime' => 'Simić Dušanka', 'adresa' => 'M.Sitarice 1 14210 Ub'],
    ['sifra' => '00358', 'ime_prezime' => 'Simeunović Radovan', 'adresa' => 'Radnička 4 14210 Ub'],
    ['sifra' => '00359', 'ime_prezime' => 'Ćurguz Slobadan', 'adresa' => 'Radnička 6 14210 Ub'],
    ['sifra' => '00360', 'ime_prezime' => 'Grujić Radoslav', 'adresa' => 'Radnička 10 14210 Ub'],
    ['sifra' => '00361', 'ime_prezime' => 'Marković Milojko', 'adresa' => 'Radnička 19 14210 Ub'],
    ['sifra' => '00362', 'ime_prezime' => 'Obradović Grozdana', 'adresa' => 'Nemanjina b.b. 15220 Koceljeva'],
    ['sifra' => '00363', 'ime_prezime' => 'Teodosić Jordan', 'adresa' => 'Kapetan Mišina 7 Beograd'],
    ['sifra' => '00364', 'ime_prezime' => 'Isailović Predrag', 'adresa' => 'Radnička 22 Ub'],
    ['sifra' => '00365', 'ime_prezime' => 'Danilović Gordana', 'adresa' => 'Radnička 25 14210 Ub'],
    ['sifra' => '00366', 'ime_prezime' => 'Radojičić Milivoje', 'adresa' => 'Radnička 13 14210 Ub'],
    ['sifra' => '00367', 'ime_prezime' => 'Nedeljković Dobrivoje', 'adresa' => 'Radnička 24 14210 Ub'],
    ['sifra' => '00368', 'ime_prezime' => 'Trifunović Branka', 'adresa' => 'Radnička 26 14210 Ub'],
    ['sifra' => '00369', 'ime_prezime' => 'Mirković Spasoje', 'adresa' => 'Radnička 43 14210 Ub'],
    ['sifra' => '00370', 'ime_prezime' => 'Lazić Dejan', 'adresa' => 'K.petra I 66 14210 Ub'],
    ['sifra' => '00371', 'ime_prezime' => 'Sarić Srbijanka', 'adresa' => 'K.Petra I 66 14210 Ub'],
    ['sifra' => '00372', 'ime_prezime' => 'Mojićević Simeun', 'adresa' => 'K.Petra I 27/12 14210 Ub'],
    ['sifra' => '00373', 'ime_prezime' => 'Marković Svetlana', 'adresa' => 'K.Petra I 24 14210 Ub'],
    ['sifra' => '00374', 'ime_prezime' => 'Radovanović Miroslav', 'adresa' => 'K Petra I 24 14210 Ub'],
    ['sifra' => '00375', 'ime_prezime' => 'Jeličić Dragoslav', 'adresa' => 'K .Petra I 72 14210 Ub'],
    ['sifra' => '00376', 'ime_prezime' => 'Jeličić Jelena', 'adresa' => 'K. Petra I 72 14210 Ub'],
    ['sifra' => '00377', 'ime_prezime' => 'Živanović Ljiljana', 'adresa' => 'K :petra I 46/2 14210 Ub'],
    ['sifra' => '00378', 'ime_prezime' => 'Mijatović Dragoslav', 'adresa' => 'M.Glišić 14210 Ub'],
    ['sifra' => '00379', 'ime_prezime' => 'Đorđević Dragan', 'adresa' => 'M.Glišić 16a 14210 Ub'],
    ['sifra' => '00380', 'ime_prezime' => 'Vasić Radmila', 'adresa' => 'M.Glišića 28a'],
    ['sifra' => '00381', 'ime_prezime' => 'Ristić Zoran', 'adresa' => 'M.Glišić 28 14210 Ub'],
    ['sifra' => '00382', 'ime_prezime' => 'Joksimović Dragan', 'adresa' => 'M.Munjasa'],
    ['sifra' => '00383', 'ime_prezime' => 'Brkić Zoran', 'adresa' => 'M:Munjasa 1 14210 Ub'],
    ['sifra' => '00385', 'ime_prezime' => 'Marinković Dobrivoje', 'adresa' => 'M.Munjasa 15 14210 Ub'],
    ['sifra' => '00387', 'ime_prezime' => 'Vuković Slobodan', 'adresa' => 'M.Munjasa 1714210 Ub'],
    ['sifra' => '00388', 'ime_prezime' => 'Simić Dragan', 'adresa' => 'M.Munjasa 19 14210 Ub'],
    ['sifra' => '00390', 'ime_prezime' => 'Nikolić Danijela', 'adresa' => 'Vuka Karadžića 14210 Ub'],
    ['sifra' => '00391', 'ime_prezime' => 'Vagić LJubica', 'adresa' => 'M.Munjasa 62'],
    ['sifra' => '00392', 'ime_prezime' => 'Mihajlović Danica', 'adresa' => 'M.Munjasa 34 14210 Ub'],
    ['sifra' => '00393', 'ime_prezime' => 'Krstić Radomir', 'adresa' => 'M.Munjasa 14210 Ub'],
    ['sifra' => '00394', 'ime_prezime' => 'Milivojević Slobodanka', 'adresa' => 'M.Munjasa 79 14210 Ub'],
    ['sifra' => '00395', 'ime_prezime' => 'Vatazević Radinka', 'adresa' => 'M.Munjasa 48 14210 Ub'],
    ['sifra' => '00396', 'ime_prezime' => 'Joksimović Miroslav', 'adresa' => 'M.Munjasa 30'],
    ['sifra' => '00397', 'ime_prezime' => 'Jakovljević Sloboodan', 'adresa' => 'M.Munjasa 66 14210 Ub'],
    ['sifra' => '00398', 'ime_prezime' => 'Lazić Jovan', 'adresa' => 'M.Munjasa 71/1 14210 Ub'],
    ['sifra' => '00399', 'ime_prezime' => 'Lazić Miroslav', 'adresa' => 'M.Munjasa 71 14210 Ub'],
    ['sifra' => '00400', 'ime_prezime' => 'Lazić Veroljub', 'adresa' => 'M.Munjasa 77 14210 Ub'],
    ['sifra' => '00401', 'ime_prezime' => 'Atlić Milan', 'adresa' => 'D.divizije 6 14210 Ub'],
    ['sifra' => '00402', 'ime_prezime' => 'Jeremić Jelica', 'adresa' => 'D.Divizije 14210 Ub'],
    ['sifra' => '00403', 'ime_prezime' => 'Paunović Jovanka', 'adresa' => 'D.Divizije 10 14210 Ub'],
    ['sifra' => '00404', 'ime_prezime' => 'Grujičić Nenad', 'adresa' => 'D.Divizije 3 14210 Ub'],
    ['sifra' => '00405', 'ime_prezime' => 'Knežević Dragan', 'adresa' => 'V.Vlahovića 11 14210 Ub'],
    ['sifra' => '00406', 'ime_prezime' => 'Marković Jovan', 'adresa' => 'Školska 2 14210 Ub'],
    ['sifra' => '00407', 'ime_prezime' => 'Milosavljević Vladimir', 'adresa' => 'Školska 14210 Ub'],
    ['sifra' => '00408', 'ime_prezime' => 'Milićević Miodrag', 'adresa' => 'B.Jovanović 2 14210 Ub'],
    ['sifra' => '00409', 'ime_prezime' => 'Popović Slavka', 'adresa' => 'B.Jovanović 4 14210 Ub'],
    ['sifra' => '00410', 'ime_prezime' => 'Ivanović Dušanka', 'adresa' => 'B.Jovanović 10'],
    ['sifra' => '00412', 'ime_prezime' => 'Stojković Zoran', 'adresa' => 'B.Jovanović 14210 Ub'],
    ['sifra' => '00413', 'ime_prezime' => 'Bađević Biserka', 'adresa' => 'B.Jovanović 9 14210 Ub'],
    ['sifra' => '00414', 'ime_prezime' => 'Spasić Danica', 'adresa' => 'M.Markovića 10 14210 Ub'],
    ['sifra' => '00415', 'ime_prezime' => 'Radovanović Petar', 'adresa' => '25.Maja 14210 Ub'],
    ['sifra' => '00416', 'ime_prezime' => 'Simić Mira', 'adresa' => 'Trlić 14210 Ub'],
    ['sifra' => '00417', 'ime_prezime' => 'Alimpijević Slobodan', 'adresa' => 'Karađorđeva 9 14210 Ub'],
    ['sifra' => '00418', 'ime_prezime' => 'Milekić Predrag', 'adresa' => 'V.Mišića 3 14210 Ub'],
    ['sifra' => '00419', 'ime_prezime' => 'Miletić Rina', 'adresa' => 'V.Mišića 3 14210 Ub'],
    ['sifra' => '00420', 'ime_prezime' => 'Marić Milovina', 'adresa' => 'V.Mišića 3 14210 Ub'],
    ['sifra' => '00421', 'ime_prezime' => 'Mitrović Dobrila', 'adresa' => 'V.Mišića 3 14210 Ub'],
    ['sifra' => '00422', 'ime_prezime' => 'Joksović Dušan', 'adresa' => 'M.Markovića 2 14210 Ub'],
    ['sifra' => '00423', 'ime_prezime' => 'Davidović Cveta', 'adresa' => 'M.Markovića 14210 Ub'],
    ['sifra' => '00424', 'ime_prezime' => 'OU Skupštine Opštine Ub PIB 101351033', 'adresa' => '3 Oktobra 3'],
    ['sifra' => '00425', 'ime_prezime' => 'Mucić Milanka', 'adresa' => 'K.Junaka 5 14210 Ub'],
    ['sifra' => '00426', 'ime_prezime' => 'Jovanović Momčilo', 'adresa' => 'K.Junaka 14210 Ub'],
    ['sifra' => '00427', 'ime_prezime' => 'Nedeljković Mile', 'adresa' => 'K.Junaka 12 14210 Ub'],
    ['sifra' => '00428', 'ime_prezime' => 'Mucić Radmila LJiljana', 'adresa' => 'K.Junaka 13'],
    ['sifra' => '00429', 'ime_prezime' => 'Milošević Slavko', 'adresa' => 'K.Junaka 1514210 Ub'],
    ['sifra' => '00430', 'ime_prezime' => 'Brajer Milan', 'adresa' => 'K.Junaka 23 Ub'],
    ['sifra' => '00431', 'ime_prezime' => 'Čarapić Slavica', 'adresa' => 'B:Marčetić 14210 Ub'],
    ['sifra' => '00432', 'ime_prezime' => 'Janjić Obrenija', 'adresa' => 'B.Marčetić 11 14210 Ub'],
    ['sifra' => '00433', 'ime_prezime' => 'Ranković Čedomir', 'adresa' => 'B.Marčetić 14 14210 Ub'],
    ['sifra' => '00434', 'ime_prezime' => 'Stojković Vesna', 'adresa' => 'B.Marčetić 16 14210 Ub'],
    ['sifra' => '00435', 'ime_prezime' => 'Radojičić Dragan', 'adresa' => 'B.Marčetić 26 14210 Ub'],
    ['sifra' => '00436', 'ime_prezime' => 'Ašković Gradimir', 'adresa' => 'R.Aleksića 2 14210 Ub'],
    ['sifra' => '00437', 'ime_prezime' => 'Lazić Gordana', 'adresa' => 'R.Aleksić 1 14210 Ub'],
    ['sifra' => '00438', 'ime_prezime' => 'Arsenović Radoje', 'adresa' => 'R.Aleksića12 14210 Ub'],
    ['sifra' => '00440', 'ime_prezime' => 'Jevtić Milena', 'adresa' => 'V.Karadžića 20 14210 Ub'],
    ['sifra' => '00441', 'ime_prezime' => 'Sarić Zorica', 'adresa' => 'V.Karadžića 20 14210 Ub'],
    ['sifra' => '00442', 'ime_prezime' => 'Marković Saša', 'adresa' => 'Trg 3 Oktobra br.2 14210Ub'],
    ['sifra' => '00443', 'ime_prezime' => 'Stanojević Radmila', 'adresa' => 'Raše Plaovića 20 Ub'],
    ['sifra' => '00444', 'ime_prezime' => 'Mitrović LJubica', 'adresa' => 'Trlić 14210 Ub'],
    ['sifra' => '00445', 'ime_prezime' => 'Pošarac Borka', 'adresa' => 'V.Karadžića 22/a 14210 Ub'],
    ['sifra' => '00446', 'ime_prezime' => 'Ćiraković Katarina', 'adresa' => 'V.Karadžića 22/A 14210 Ub'],
    ['sifra' => '00447', 'ime_prezime' => 'Popadić Velimir', 'adresa' => '3:Oktobra 2 14210 Ub'],
    ['sifra' => '00449', 'ime_prezime' => 'Andonović Jasmina', 'adresa' => '3.Oktobra 2 Ub'],
    ['sifra' => '00450', 'ime_prezime' => 'Nedić Zlata', 'adresa' => '3.Oktobra 6 Ub'],
    ['sifra' => '00451', 'ime_prezime' => 'Atanacković Nikola', 'adresa' => '3.Oktobra 6 14210 Ub'],
    ['sifra' => '00452', 'ime_prezime' => 'Lazić Nadežda', 'adresa' => '3.Oktobra 6 Ub'],
    ['sifra' => '00453', 'ime_prezime' => 'Petrović Goran', 'adresa' => '3.Oktobra 8 14210 Ub'],
    ['sifra' => '00454', 'ime_prezime' => 'Đukanović Grozdana', 'adresa' => '3.Oktobra 8 14210 Ub'],
    ['sifra' => '00455', 'ime_prezime' => 'Ostojić Radovan', 'adresa' => 'B.Petronijević 2 14210 Ub'],
    ['sifra' => '00456', 'ime_prezime' => 'Lazarić Vesna', 'adresa' => 'B.Petronijević 5 14210 Ub'],
    ['sifra' => '00457', 'ime_prezime' => 'Urošević Dušan', 'adresa' => 'B.Petronijević 11 14210 Ub'],
    ['sifra' => '00458', 'ime_prezime' => 'Mirčić Živka', 'adresa' => 'B.Petronijević 8 14210 Ub'],
    ['sifra' => '00459', 'ime_prezime' => 'Vesić Aleksandar', 'adresa' => 'B.Petronijević 21 14210 Ub'],
    ['sifra' => '00460', 'ime_prezime' => 'Miličić Veroljub', 'adresa' => 'B.Petronijević 14 14210 Ub'],
    ['sifra' => '00461', 'ime_prezime' => 'Višnjić LJiljana', 'adresa' => '29.Novembra 4 Ub'],
    ['sifra' => '00462', 'ime_prezime' => 'Maksić Vera', 'adresa' => '29.Novembra 6 UB'],
    ['sifra' => '00463', 'ime_prezime' => 'Savić Dragan', 'adresa' => '29.Novembra 14210 Ub'],
    ['sifra' => '00464', 'ime_prezime' => 'Luković Ivan', 'adresa' => 'Lamela 1/6'],
    ['sifra' => '00465', 'ime_prezime' => 'Čanić LJubica', 'adresa' => 'Lamela 1/3 14210 Ub'],
    ['sifra' => '00466', 'ime_prezime' => 'Živanović Despot', 'adresa' => 'Lamela 2 Ub'],
    ['sifra' => '00467', 'ime_prezime' => 'Golubović Danica', 'adresa' => 'Lamela 2/8 14210 Ub'],
    ['sifra' => '00468', 'ime_prezime' => 'Puletić Radovan', 'adresa' => 'Lamela 2 14210 Ub'],
    ['sifra' => '00469', 'ime_prezime' => 'Sandić Danica', 'adresa' => 'Lamela 2/17 14210 Ub'],
    ['sifra' => '00470', 'ime_prezime' => 'Munitlak Dragan', 'adresa' => 'Lamela 3 14210 UB'],
    ['sifra' => '00471', 'ime_prezime' => 'Glišić Dragan', 'adresa' => 'Lamela 3 14210 Ub'],
    ['sifra' => '00473', 'ime_prezime' => 'Marjanović Jelena', 'adresa' => 'Lamela 3 14210 Ub'],
    ['sifra' => '00474', 'ime_prezime' => 'Jovanović Vidosava', 'adresa' => 'Lamela 3 14210 Ub'],
    ['sifra' => '00475', 'ime_prezime' => 'Šipčić Dušica', 'adresa' => 'Lamela 3 Ub'],
    ['sifra' => '00477', 'ime_prezime' => 'Matović Slobodan', 'adresa' => 'Lamela 3 Ub 14210 Ub'],
    ['sifra' => '00478', 'ime_prezime' => 'Jovanović Dragivoj', 'adresa' => 'Lamela 4'],
    ['sifra' => '00480', 'ime_prezime' => 'Petković Olga', 'adresa' => 'Lamela 4/16 14210 Ub'],
    ['sifra' => '00481', 'ime_prezime' => 'Adamović Miroslava', 'adresa' => 'Lamela 5/7 14210 Ub'],
    ['sifra' => '00482', 'ime_prezime' => 'Mijatović Dragana', 'adresa' => 'J.Majera 14210 Ub'],
    ['sifra' => '00483', 'ime_prezime' => 'Todorić Miloš', 'adresa' => '1.Maja 23 14210 Ub'],
    ['sifra' => '00484', 'ime_prezime' => 'Živanović Slobodan', 'adresa' => 'J.Majera 49 14210 Ub'],
    ['sifra' => '00485', 'ime_prezime' => 'Atlić Slavko', 'adresa' => 'J.Majera Ub'],
    ['sifra' => '00486', 'ime_prezime' => 'Adamović Dragan', 'adresa' => 'J.Majera 14210 Ub'],
    ['sifra' => '00487', 'ime_prezime' => 'Stanojević Živorad', 'adresa' => 'J.Majera 14210 Ub'],
    ['sifra' => '00488', 'ime_prezime' => 'Cvetojević Vojislav', 'adresa' => 'J.Majera 14210 Ub'],
    ['sifra' => '00489', 'ime_prezime' => 'Perišić Veroljub', 'adresa' => 'J.Majera 14210 Ub'],
    ['sifra' => '00490', 'ime_prezime' => 'Jovanović Zoran', 'adresa' => 'J.Majera 14210 Ub'],
    ['sifra' => '00491', 'ime_prezime' => 'Bilić Radosav', 'adresa' => 'J.Majera 14210 Ub'],
    ['sifra' => '00492', 'ime_prezime' => 'Tadić Goran', 'adresa' => 'J.Majera 110 14210 Ub'],
    ['sifra' => '00493', 'ime_prezime' => 'Pajčić Milorad', 'adresa' => 'J.Majera 14210 Ub'],
    ['sifra' => '00494', 'ime_prezime' => 'Milić Milutin', 'adresa' => 'Ul.Josipa Majera 93 14210 Ub'],
    ['sifra' => '00496', 'ime_prezime' => 'Leontijević Milijan', 'adresa' => 'J.Majera 14210 Ub'],
    ['sifra' => '00497', 'ime_prezime' => 'Lukić Vladimir', 'adresa' => 'J.Majera 14210 Ub'],
    ['sifra' => '00498', 'ime_prezime' => 'Gavrilović Antonije', 'adresa' => 'J.Majera 95 14210 Ub'],
    ['sifra' => '00499', 'ime_prezime' => 'Atlić Radoje', 'adresa' => 'J.Majera 14210 Ub'],
    ['sifra' => '00500', 'ime_prezime' => 'Atlić Radoslav', 'adresa' => 'J.Majera'],
    ['sifra' => '00501', 'ime_prezime' => 'Leontijević LJubivoj', 'adresa' => 'J.Majera 77 14210 Ub'],
    ['sifra' => '00502', 'ime_prezime' => 'Kovačević Dragislav', 'adresa' => 'J.Majera 65 Ub'],
    ['sifra' => '00503', 'ime_prezime' => 'Tanasijević Radojka', 'adresa' => 'J.Majera 14210 Ub'],
    ['sifra' => '00504', 'ime_prezime' => 'Kojić Dragoslav', 'adresa' => 'J.Majera 61'],
    ['sifra' => '00505', 'ime_prezime' => 'Vasiljević Božidarka', 'adresa' => 'J.Majera 14210 Ub'],
    ['sifra' => '00506', 'ime_prezime' => 'Gajić Vladan', 'adresa' => 'J.Majera 57/1 14210 Ub'],
    ['sifra' => '00507', 'ime_prezime' => 'Grujičić Nadežda', 'adresa' => 'J.Majera 76 14210'],
    ['sifra' => '00508', 'ime_prezime' => 'Damjanović LJubomir', 'adresa' => 'J.Majera 70 14210 Ub'],
    ['sifra' => '00509', 'ime_prezime' => 'Božić Zoran', 'adresa' => 'J.Majera 55 14210 Ub'],
    ['sifra' => '00510', 'ime_prezime' => 'Janković Miroslav', 'adresa' => 'J.Majera 64 14210 Ub'],
    ['sifra' => '00511', 'ime_prezime' => 'Jagodić Dragica', 'adresa' => 'J.Majera 39/1 14210 Ub'],
    ['sifra' => '00512', 'ime_prezime' => 'Gligorijević Jovica', 'adresa' => 'J.Majera 35 Ub'],
    ['sifra' => '00513', 'ime_prezime' => 'Stanišić Zoran', 'adresa' => 'J.Majera 60 14210 Ub'],
    ['sifra' => '00514', 'ime_prezime' => 'Urošević Milan', 'adresa' => 'J.Majera 52 14210 Ub'],
    ['sifra' => '00515', 'ime_prezime' => 'Jovanović Dragoljub', 'adresa' => 'J.Majera 23 14210 Ib'],
    ['sifra' => '00516', 'ime_prezime' => 'Ječmenica Milojko', 'adresa' => 'J.Majera 19 14210 Ub'],
    ['sifra' => '00517', 'ime_prezime' => 'Jadžić Veran', 'adresa' => 'J.Majera 42 14210 Ub'],
    ['sifra' => '00518', 'ime_prezime' => 'Ječmenica Zoran', 'adresa' => 'J.Majera 17 14210 Ub'],
    ['sifra' => '00519', 'ime_prezime' => 'Ječmenica Milan', 'adresa' => 'J.Majera 15'],
    ['sifra' => '00520', 'ime_prezime' => 'Martić Dragana', 'adresa' => 'Braće Jovanović 18 14210 Ub'],
    ['sifra' => '00521', 'ime_prezime' => 'Ivković Nenad', 'adresa' => 'J.Majera14 14210 Ub'],
    ['sifra' => '00522', 'ime_prezime' => 'Rajković Goran', 'adresa' => 'J.Majera 22 14210 Ub'],
    ['sifra' => '00523', 'ime_prezime' => 'Kiselčić Bogdan', 'adresa' => 'J.Majera 13 14210 Ub'],
    ['sifra' => '00524', 'ime_prezime' => 'Teodosić Jordan', 'adresa' => 'Kapetan Mišina 7 Beograd'],
    ['sifra' => '00525', 'ime_prezime' => 'Plakalović Ilija', 'adresa' => '8.Marta 10 14210 Ub'],
    ['sifra' => '00526', 'ime_prezime' => 'Kristić Zorica', 'adresa' => 'Beograd Sime Igumanova 18 12sp. st.76'],
    ['sifra' => '00528', 'ime_prezime' => 'Nikolić Stana', 'adresa' => 'Tamnavskih Partizana 4 Ub'],
    ['sifra' => '00530', 'ime_prezime' => 'Ignjatović Anđa', 'adresa' => 'Braće Marčetič 24 Ub'],
    ['sifra' => '00531', 'ime_prezime' => 'Marković J Dragomir', 'adresa' => 'Potočari br.11 Ub'],
    ['sifra' => '00532', 'ime_prezime' => 'Blizanjac Srboljub', 'adresa' => 'Osma Crnogorska br.9 14210 Ub'],
    ['sifra' => '00533', 'ime_prezime' => 'Jovanović Božidar', 'adresa' => 'JNA 157 Ub'],
    ['sifra' => '00534', 'ime_prezime' => 'Pravik Josip', 'adresa' => 'Osmog marta br.9 Ub'],
    ['sifra' => '00535', 'ime_prezime' => 'Tešić Dobrica', 'adresa' => 'Sestara Rebavki Lam.4 st.17 14210 Ub'],
    ['sifra' => '00536', 'ime_prezime' => 'Katanić Snežana', 'adresa' => 'Vojvode Mišić br.32 14210 Ub'],
    ['sifra' => '00537', 'ime_prezime' => 'Gardinovački Saša', 'adresa' => 'JNA 87 Ub 14210 Ub'],
    ['sifra' => '00538', 'ime_prezime' => 'Kujundžić Ilinka', 'adresa' => 'Stepanje'],
    ['sifra' => '00539', 'ime_prezime' => 'Ninković Jelisaveta', 'adresa' => 'Veljka Vlahivić br.5 14210 Ub'],
    ['sifra' => '00540', 'ime_prezime' => 'Stajčić Ratko', 'adresa' => 'Sestara Rebavki 3 st.17 14210 Ub'],
    ['sifra' => '00541', 'ime_prezime' => 'Majstorović Dragiša', 'adresa' => 'Braće Nenadović 14210 Ub'],
    ['sifra' => '00542', 'ime_prezime' => 'Mitrović Branivoj', 'adresa' => 'Ul.oslobodioci Valjeva Valjevo 14000'],
    ['sifra' => '00543', 'ime_prezime' => 'Mitrović Zivodarka', 'adresa' => 'Valjevo Naselje Oslobodioci Valjeva 1/4'],
    ['sifra' => '00544', 'ime_prezime' => 'Blagojević Branko', 'adresa' => 'Braće Nenadović 10 Ub'],
    ['sifra' => '00545', 'ime_prezime' => 'Kosanić Stana', 'adresa' => 'K.P.Oslobodioca Ub'],
    ['sifra' => '00546', 'ime_prezime' => 'Mendragić Milica', 'adresa' => 'Potočari br.6 Ub'],
    ['sifra' => '00547', 'ime_prezime' => 'Snegić Novak', 'adresa' => 'Karađorđeva 75/2 14000 Valjevo'],
    ['sifra' => '00548', 'ime_prezime' => 'Stanojević Dragoljub', 'adresa' => 'Cvijićeva 112-120 11000 Beograd'],
    ['sifra' => '00549', 'ime_prezime' => 'Petrović Mihailo', 'adresa' => 'Žarkovačka 29 11030 Beograd'],
    ['sifra' => '00550', 'ime_prezime' => 'Radivojević Vida', 'adresa' => 'Vojvode Mišić 38 Ub'],
    ['sifra' => '00551', 'ime_prezime' => 'Petrović Slaviša', 'adresa' => 'Puje Pandurović Ub'],
    ['sifra' => '00552', 'ime_prezime' => 'Vasović Vasa', 'adresa' => 'Kralja Vladimira 28 11010 Beograd'],
    ['sifra' => '00553', 'ime_prezime' => 'Stanojlović Živana', 'adresa' => 'Dušana Danilović Ub'],
    ['sifra' => '00554', 'ime_prezime' => 'Đurašinović Gordana', 'adresa' => 'Kralja Petra I 3214210 Ub'],
    ['sifra' => '00555', 'ime_prezime' => 'Tanasković Srđan', 'adresa' => 'Veliko Polje 17 11507 Stubline'],
    ['sifra' => '00556', 'ime_prezime' => 'Joksimović Snežana', 'adresa' => 'Braće Nenadović br.2 Ub'],
    ['sifra' => '00557', 'ime_prezime' => 'Radojčić Dragan', 'adresa' => 'JNA 63 14210 Ub'],
    ['sifra' => '00558', 'ime_prezime' => 'Lazić Dragan', 'adresa' => 'Vuka Karadžić 50 Lajkovac'],
    ['sifra' => '00559', 'ime_prezime' => 'Đokić -Vojinović Nadežda', 'adresa' => 'Murgaš Ub'],
    ['sifra' => '00560', 'ime_prezime' => 'Aleksandrić Radovan', 'adresa' => 'Trnjaci 14210 Ub'],
    ['sifra' => '00561', 'ime_prezime' => 'Filipović Milan', 'adresa' => 'JNA 52/1 14210 Ub'],
    ['sifra' => '00563', 'ime_prezime' => 'Nestorović Slađana', 'adresa' => 'Bulevar Avnoja 88 11000 Beograd'],
    ['sifra' => '00564', 'ime_prezime' => 'Mišić Slobodan', 'adresa' => 'Josipa Majera 12 14210 Ub'],
    ['sifra' => '00565', 'ime_prezime' => 'Marković Rosa', 'adresa' => 'Prvog Maja 140 14210 Ub'],
    ['sifra' => '00566', 'ime_prezime' => 'Stefanović Dragana', 'adresa' => 'Mileševska 24 11000 Beograd'],
    ['sifra' => '00567', 'ime_prezime' => 'Jakovljević Dušan', 'adresa' => 'JNA 88 14210 Ub'],
    ['sifra' => '00568', 'ime_prezime' => 'Ašković Siniša', 'adresa' => 'Josipa Majera 56 14210 Ub'],
    ['sifra' => '00569', 'ime_prezime' => 'Jovanović Borisav', 'adresa' => 'KP Oslobodioca 44 Ub'],
    ['sifra' => '00570', 'ime_prezime' => 'Jeličić Mirjana', 'adresa' => 'Kosovskih junaka 16 14210 Ub'],
    ['sifra' => '00571', 'ime_prezime' => 'Gajić Dragica', 'adresa' => 'Milana Munjasa Ub'],
    ['sifra' => '00572', 'ime_prezime' => 'Janković Zdravko', 'adresa' => 'Neimarska br.2 14210 Ub'],
    ['sifra' => '00573', 'ime_prezime' => 'Ašković Gordana', 'adresa' => 'Janka Veselinović BR.4 14210 Ub'],
    ['sifra' => '00574', 'ime_prezime' => 'Nikolić Mirjana', 'adresa' => 'Prvog Maja 35 14210 Ub'],
    ['sifra' => '00575', 'ime_prezime' => 'Radaković Miroslav', 'adresa' => 'Svete Popović Ub'],
    ['sifra' => '00576', 'ime_prezime' => 'Lukić Dragan', 'adresa' => 'Braće Marčetić 10 14210 Ub'],
    ['sifra' => '00577', 'ime_prezime' => 'Pavlović Mirjana', 'adresa' => 'Potočari 13 Ub'],
    ['sifra' => '00578', 'ime_prezime' => 'Rakić Savka', 'adresa' => 'Berane'],
    ['sifra' => '00579', 'ime_prezime' => 'Fesović Predrag', 'adresa' => 'Miloša Selaković 2 14210 Ub'],
    ['sifra' => '00580', 'ime_prezime' => 'Milićević Dragoljub', 'adresa' => 'Josipa Majera 30 14210 Ub'],
    ['sifra' => '00581', 'ime_prezime' => 'Cikuša Jugoslav', 'adresa' => 'Novi Sad Stevana Sremca 17'],
    ['sifra' => '00582', 'ime_prezime' => 'Živanović Milorad', 'adresa' => 'Josipa Majera Ub'],
    ['sifra' => '00583', 'ime_prezime' => 'Petrović Milunka', 'adresa' => 'Prvog Maja 70 14210 Ub'],
    ['sifra' => '00584', 'ime_prezime' => 'Pavlović LJubina', 'adresa' => 'Vojvode Micka 21 Beograd'],
    ['sifra' => '00585', 'ime_prezime' => 'Jovanović Živodarka', 'adresa' => 'Dragoslava Tomić 2 Ub'],
    ['sifra' => '00586', 'ime_prezime' => 'Stanojević Darko', 'adresa' => 'Josipa Majera 16 Ub'],
    ['sifra' => '00587', 'ime_prezime' => 'Rakić Jelisaveta', 'adresa' => 'Milovana Glišić 14210 Ub'],
    ['sifra' => '00588', 'ime_prezime' => 'Šabotić Smajo', 'adresa' => 'Berane'],
    ['sifra' => '00589', 'ime_prezime' => 'Đorđević Živodarka', 'adresa' => 'Svete Popović 9714210 Ub'],
    ['sifra' => '00590', 'ime_prezime' => 'Bekčić Dragica', 'adresa' => 'Miloša Selaković 13 14210 Ub'],
    ['sifra' => '00591', 'ime_prezime' => 'Novaković Jelica', 'adresa' => 'Potočari 9 Ub'],
    ['sifra' => '00592', 'ime_prezime' => 'Ašković Spasoje', 'adresa' => 'Sestara Rebavk 4/10. 14210 Ub'],
    ['sifra' => '00593', 'ime_prezime' => 'Stanković Vojislav', 'adresa' => 'Svete Popović 100 14210 Ub'],
    ['sifra' => '00594', 'ime_prezime' => 'Paripović Dragan', 'adresa' => 'Vojvode Milenka 52 st.7 11000 Beograd'],
    ['sifra' => '00595', 'ime_prezime' => 'Lukić Čedomir', 'adresa' => 'Milana Munjasa 14210 Ub'],
    ['sifra' => '00596', 'ime_prezime' => 'Krivošić Željko', 'adresa' => 'Prvog Maja 14210 Ub'],
    ['sifra' => '00597', 'ime_prezime' => 'Milinković Slobodan', 'adresa' => 'Slavoljuba Milivojević 11 14210 Ub'],
    ['sifra' => '00598', 'ime_prezime' => 'Maciejonczyk Ruža', 'adresa' => 'Slavoljuba Milivojević 4 Ub'],
    ['sifra' => '00599', 'ime_prezime' => 'Mijailović Milena', 'adresa' => 'Senjačka br.9 11040 Beograd'],
    ['sifra' => '00600', 'ime_prezime' => 'Mitrović Vesna', 'adresa' => 'Feješ Klare br.66 21000 Novi Sad'],
    ['sifra' => '00601', 'ime_prezime' => 'Živković Svetlana', 'adresa' => 'Grobljanska 17 Ub'],
    ['sifra' => '00602', 'ime_prezime' => 'Krsmanović Danica', 'adresa' => 'Braće Nenadović Ub'],
    ['sifra' => '00603', 'ime_prezime' => 'Zaklan Slobodan', 'adresa' => 'Kosovskih Junaka 14210 Ub'],
    ['sifra' => '00604', 'ime_prezime' => 'Jovanović Slavka', 'adresa' => 'Braće Nenadović 11 Ub'],
    ['sifra' => '00605', 'ime_prezime' => 'Stanojević Stanoje', 'adresa' => 'Svete Popović 126 14210 Ub'],
    ['sifra' => '00606', 'ime_prezime' => 'Bogdanović Anđelija', 'adresa' => 'Živote Ilić br.2 14210 Ub'],
    ['sifra' => '00607', 'ime_prezime' => 'Veselinović Milan', 'adresa' => 'Birčaninova 4A/13 11000 Beograd'],
    ['sifra' => '00608', 'ime_prezime' => 'Zec Oliver', 'adresa' => 'Norveških Interniraca 5 14210 Ub'],
    ['sifra' => '00609', 'ime_prezime' => 'Jovanić Milan', 'adresa' => 'Vuka Karadžića 14/1 14210 Ub'],
    ['sifra' => '00610', 'ime_prezime' => 'Andrić Zorica', 'adresa' => 'Milivoja Bjelice 14 a Ulaz 2 st.26 14000 Valjevo'],
    ['sifra' => '00611', 'ime_prezime' => 'Živković Ružica', 'adresa' => 'Braće Nenadović 14210 Ub'],
    ['sifra' => '00612', 'ime_prezime' => 'Joksimović Zlata', 'adresa' => 'Braće Nenadović 2 14210 Ub'],
    ['sifra' => '00613', 'ime_prezime' => 'Bjelogrlić Sonja', 'adresa' => 'Kralja Petra I Oslobodioca 27/8 14210 Ub'],
    ['sifra' => '00614', 'ime_prezime' => 'Vulešević Dragan', 'adresa' => 'Tržička 10 11050 Beograd'],
    ['sifra' => '00615', 'ime_prezime' => 'Zafirović Danica', 'adresa' => 'Katanićeva 18 11000 Vračar'],
    ['sifra' => '00616', 'ime_prezime' => 'Jovanović Svetlana', 'adresa' => 'Cerska 18 Vračar stan 7 Beograd'],
    ['sifra' => '00617', 'ime_prezime' => 'Vićentijević Vekoslav', 'adresa' => 'Nikole Mišljenović 21 Ub'],
    ['sifra' => '00618', 'ime_prezime' => 'Maksić Dragoljub', 'adresa' => 'Braće Nenadović 3 14210 Ub'],
    ['sifra' => '00619', 'ime_prezime' => 'Radovanović Spasoje', 'adresa' => 'Golubačka 10 11000 Beograd'],
    ['sifra' => '00620', 'ime_prezime' => 'Vikić Milojka', 'adresa' => 'Aleksandra Simović 3 11500 Obrenovac'],
    ['sifra' => '00621', 'ime_prezime' => 'Šljivić Milosav', 'adresa' => 'Milana Munjasa 4614210 Ub'],
    ['sifra' => '00622', 'ime_prezime' => 'Pajić Radenka', 'adresa' => 'Radnička 76 Ub'],
    ['sifra' => '00623', 'ime_prezime' => 'Kostić Branka', 'adresa' => 'Rajka Mihailović 14 Ub'],
    ['sifra' => '00624', 'ime_prezime' => 'Mićić Dragan', 'adresa' => 'Svete Popović 93 Ub'],
    ['sifra' => '00625', 'ime_prezime' => 'Ninković Otilija', 'adresa' => 'Braće Jovanović Ub'],
    ['sifra' => '00626', 'ime_prezime' => 'Srećković Olgica', 'adresa' => 'Ub, Ul,Prvog Maja Ub'],
    ['sifra' => '00627', 'ime_prezime' => 'Buinac Slavko', 'adresa' => 'Ilije Milovanović 17 34300 Aranđelovac'],
    ['sifra' => '00628', 'ime_prezime' => 'Ćućić Nataša', 'adresa' => 'Beograd Kraljice Marije 10 11000 Beograd'],
    ['sifra' => '00629', 'ime_prezime' => 'Nikolić Slađana', 'adresa' => 'Prvog Maja 142 Ub'],
    ['sifra' => '00630', 'ime_prezime' => 'Vukmirović Snežana', 'adresa' => 'Braće Nenadović 6 Ub'],
    ['sifra' => '00631', 'ime_prezime' => 'Mijatović Olivera', 'adresa' => 'Miloša Selaković 14210 Ub'],
    ['sifra' => '00632', 'ime_prezime' => 'Petrović Snežana', 'adresa' => 'Ive Andrića 6 14210 Ub'],
    ['sifra' => '00633', 'ime_prezime' => 'Milić Milutin', 'adresa' => 'Trnjaci Ub'],
    ['sifra' => '00634', 'ime_prezime' => 'Mlađenović Nevena', 'adresa' => 'Miloša Marković Ub'],
    ['sifra' => '00635', 'ime_prezime' => 'Ostojić Radosav', 'adresa' => 'JNA 88 Ub'],
    ['sifra' => '00636', 'ime_prezime' => 'Jovanović Željka', 'adresa' => 'Ub, Vuka Karadžića 1'],
    ['sifra' => '00637', 'ime_prezime' => 'Denda Stana', 'adresa' => 'Sestara Rebavki lam.V st.10 Ub'],
    ['sifra' => '00638', 'ime_prezime' => 'Kuzeljević Miladin', 'adresa' => 'Murgaš Ub 14210'],
    ['sifra' => '00639', 'ime_prezime' => 'Milković Ljiljana', 'adresa' => 'Ub,'],
    ['sifra' => '00640', 'ime_prezime' => 'Maldaner Veselin', 'adresa' => 'Vrbnička 1a/2 Beograd 11090'],
    ['sifra' => '00641', 'ime_prezime' => 'Lukić Zoran', 'adresa' => 'Tamnavskih Partizana 38 Ub'],
    ['sifra' => '00642', 'ime_prezime' => 'Rogić Milena', 'adresa' => 'Kolubarska 8 Ub'],
    ['sifra' => '00643', 'ime_prezime' => 'Radosavljević Lale', 'adresa' => 'Braće Jovanović 14 Ub'],
    ['sifra' => '00644', 'ime_prezime' => 'Lelićanin Ilija', 'adresa' => 'Janka Veselinović 13 Ub'],
    ['sifra' => '00645', 'ime_prezime' => 'Radovanović Milena', 'adresa' => 'Bratstva Jedinstva 30 Ub'],
    ['sifra' => '00646', 'ime_prezime' => 'Radičević Olivera', 'adresa' => 'Ul 16 Oktobra 19/2 11060 Beograd'],
    ['sifra' => '00647', 'ime_prezime' => 'Savić Nikola', 'adresa' => 'Beograd Beogradska 59 11000 Beograd'],
    ['sifra' => '00648', 'ime_prezime' => 'Jovanović Ljiljiljana', 'adresa' => 'Slavoljuba Milivojević lam.I ST.12 14210 Ub'],
    ['sifra' => '00649', 'ime_prezime' => 'Crnogorac Ilinka', 'adresa' => 'Raše Plaović 22 Ub'],
    ['sifra' => '00650', 'ime_prezime' => 'Jakovljević Radmila', 'adresa' => 'K.P.I Oslobodioca Ub'],
    ['sifra' => '00651', 'ime_prezime' => 'OU Skupšrine Opštine Ub Pib 101351033', 'adresa' => '3 Oktobra br.3'],
    ['sifra' => '00652', 'ime_prezime' => 'Milić Draga', 'adresa' => 'Trnjaci Ub'],
    ['sifra' => '00653', 'ime_prezime' => 'Kuzmanović Milorad', 'adresa' => 'Smederevska Palanka Bul.Kralja Petra I 81/1 11420'],
    ['sifra' => '00654', 'ime_prezime' => 'Popović Mileva', 'adresa' => 'Radljevo 14211Radljevo'],
    ['sifra' => '00655', 'ime_prezime' => 'Martić Ljiljana', 'adresa' => 'JNA 137 Ub'],
    ['sifra' => '00656', 'ime_prezime' => 'Todorović Jelka', 'adresa' => 'Majdanska br.23 11500 Obrenovac'],
    ['sifra' => '00657', 'ime_prezime' => 'Stanković Dragan', 'adresa' => 'Milene Sitarice 2 Ub'],
    ['sifra' => '00658', 'ime_prezime' => 'Rakić Nemanja', 'adresa' => 'Potočari 10 Ub'],
    ['sifra' => '00659', 'ime_prezime' => 'Pavlović Radojica', 'adresa' => 'Potočari br.1 Ub'],
    ['sifra' => '00660', 'ime_prezime' => 'Runjajić Ratomir', 'adresa' => 'Puje Pandurović 2 Ub'],
    ['sifra' => '00661', 'ime_prezime' => 'Ristić Stana', 'adresa' => 'Braće Nenadović 22 Ub'],
    ['sifra' => '00662', 'ime_prezime' => 'Stanković Dobrivoje', 'adresa' => 'Kosovskih Junaka Ub'],
    ['sifra' => '00663', 'ime_prezime' => 'Ristić Miroljub', 'adresa' => 'Kupinovo Orašačka 13 22419'],
    ['sifra' => '00664', 'ime_prezime' => 'Babić Olivera', 'adresa' => 'Ub, Kralja Petra I'],
    ['sifra' => '00665', 'ime_prezime' => 'Milanović Stevan', 'adresa' => 'Ub, Brane Petronijević 12'],
    ['sifra' => '00666', 'ime_prezime' => 'Davidović Gordana', 'adresa' => 'Ub, Ul.B.Nenadović'],
    ['sifra' => '00667', 'ime_prezime' => 'Paramentić Ivanka', 'adresa' => '3 Oktobra br.6 Ub'],
    ['sifra' => '00668', 'ime_prezime' => 'Perić Olivera', 'adresa' => 'Osma Crnogorska 11 Ub'],
    ['sifra' => '00669', 'ime_prezime' => 'Mirković Branka', 'adresa' => 'Moše Pijade Ub'],
    ['sifra' => '00670', 'ime_prezime' => 'Džajić Ljubinka', 'adresa' => 'Omladinskih Brigada Ub'],
    ['sifra' => '00672', 'ime_prezime' => 'Petronijević Miroslav', 'adresa' => 'Braće Nenadović Ub'],
    ['sifra' => '00673', 'ime_prezime' => 'Petrović Milorad', 'adresa' => 'Tamnavska 37 Ub'],
    ['sifra' => '00674', 'ime_prezime' => 'Lazić Ljiljana', 'adresa' => 'Milana Munjasa 26 Ub'],
    ['sifra' => '00675', 'ime_prezime' => 'Isailović Dušanka', 'adresa' => 'Josipa Majera 7314210 Ub'],
    ['sifra' => '00676', 'ime_prezime' => 'Obućinski Gordana', 'adresa' => 'JNA 121 Ub'],
    ['sifra' => '00677', 'ime_prezime' => 'Ostojić Milena', 'adresa' => 'JNA 88 Ub'],
    ['sifra' => '00678', 'ime_prezime' => 'Gardinovački Vladimir', 'adresa' => 'JNA 89 Ub'],
    ['sifra' => '00679', 'ime_prezime' => 'Majstorović Vig Zlatija', 'adresa' => 'Vršačka 12 Pančevo 26000'],
    ['sifra' => '00680', 'ime_prezime' => 'Petrić Mladen', 'adresa' => 'Vuka Karadžića 13 Ub'],
    ['sifra' => '00681', 'ime_prezime' => 'Maletić Radovan', 'adresa' => 'Ub, JNA 79/1'],
    ['sifra' => '00682', 'ime_prezime' => 'Jakovljević Milan', 'adresa' => 'Kralja Petra Oslobodioca 54 Ub'],
    ['sifra' => '00683', 'ime_prezime' => 'Brujić Mira', 'adresa' => 'Pionirska 6 14210 Ub'],
    ['sifra' => '00684', 'ime_prezime' => 'Nedeljković Branko', 'adresa' => 'Aleksića Imanje br.8'],
    ['sifra' => '00685', 'ime_prezime' => 'Lazić Božana', 'adresa' => 'Smiljanićeva 27 Vračar Beograd'],
    ['sifra' => '00686', 'ime_prezime' => 'Đurđević Milorad', 'adresa' => 'Trnjaci Ub'],
    ['sifra' => '00687', 'ime_prezime' => 'Ranković Dragiša', 'adresa' => 'Tamnavska bb 11500 Obrenovac'],
    ['sifra' => '00688', 'ime_prezime' => 'Milićević Cvetko', 'adresa' => 'Ul.Zorice Božović Jajinci Beograd'],
    ['sifra' => '00689', 'ime_prezime' => 'Vezmar Dragica', 'adresa' => '25 Maja br.5 Ub'],
    ['sifra' => '00690', 'ime_prezime' => 'Nešić Milka', 'adresa' => 'Mirijevski Bulevar 2 11000 Beograd'],
    ['sifra' => '00691', 'ime_prezime' => 'Pavlović Radisav', 'adresa' => 'JNA 14210 Ub'],
    ['sifra' => '00692', 'ime_prezime' => 'Radojičić Raja', 'adresa' => 'Braće Marčetić 28 Ub'],
    ['sifra' => '00693', 'ime_prezime' => 'Osnovni Sud Valjevo PIB 101348202', 'adresa' => 'Karađrđeva 50 14000 Valjevo'],
    ['sifra' => '00694', 'ime_prezime' => 'Popović Snežana', 'adresa' => 'Ustanička br.1 14210 Ub'],
    ['sifra' => '00695', 'ime_prezime' => 'Branković Stana', 'adresa' => '8 Crnogorska br.17 14210 Ub'],
    ['sifra' => '00696', 'ime_prezime' => 'Jagodić Gordana', 'adresa' => 'Ub, Braće Marčetić 2']
        ];

        foreach ($uplatilacs as $u) {
            Uplatilac::create($u);
        }
    }
} 